import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import "./globals.css";


const firaCode = Fira_Code({
   variable : "--font-fira-code",
   subsets: ["latin"],
   weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${firaCode.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
